### ISSUE TITLE
Chat about Digital Sustainability

### ISSUE THREAD

**Issue by notmariazoe** [sirdmon/das#1]
Hey David,

Hope all is well!

I've been looking through your digital sustainability research and I would love to be able to touch base on the topic if you're interested.

Do you have an email I could reach out to you on? I haven't been able to find any social links for you unfortunately. I'm happy to share more details there! :)

**Comment by sirdmon** [comment]
@notmariazoe  Share your thoughts at **digital.audits:apple:protonmail.com**
